package store

import (
	"database/sql"
	"errors"
	"fmt"

	"github.com/connorpodea/splitit/internal/models"
)

// CreateUser inserts a new user record into the database.
// The password hash must be generated by the caller before this method is invoked.
func (s *Store) CreateUser(user *models.User) error {
	query := `
	INSERT INTO users
	(id, password_hash, name, email, phone_number, balance_cents, credit_score, credit_limit_cents)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?);`

	_, err := s.db.Exec(query, user.ID, user.PasswordHash, user.Name, user.Email, user.PhoneNumber, user.BalanceCents, user.CreditScore, user.CreditLimitCents)
	if err != nil {
		return fmt.Errorf("failed to write profile for user ID '%s' to database: %w", user.ID, err)
	}
	return nil
}

// GetUser retrieves the full user record including password hash and is_active status by ID.
// Does not filter by is_active so the auth layer can distinguish "not found" from "deactivated".
func (s *Store) GetUser(userID string) (*models.User, error) {
	query := `
	SELECT id, password_hash, name, email, phone_number, balance_cents, credit_score, credit_limit_cents, is_active, profile_color, created_at
	FROM users
	WHERE id = ?;`
	var user models.User
	var isActiveInt int

	err := s.db.QueryRow(query, userID).Scan(
		&user.ID,
		&user.PasswordHash,
		&user.Name,
		&user.Email,
		&user.PhoneNumber,
		&user.BalanceCents,
		&user.CreditScore,
		&user.CreditLimitCents,
		&isActiveInt,
		&user.ProfileColor,
		&user.CreatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("user account not found for ID '%s': %w", userID, err)
		}
		return nil, fmt.Errorf("failed to retrieve full account parameters for user ID '%s': %w", userID, err)
	}

	user.IsActive = isActiveInt == 1
	return &user, nil
}

// GetProfile retrieves the public-facing profile for an active user by ID.
// Returns not found if the user is deactivated.
func (s *Store) GetProfile(id string) (*models.Profile, error) {
	query := `
	SELECT id, name, email, phone_number, profile_color, created_at
	FROM users
	WHERE id = ? AND is_active = 1;`
	var profile models.Profile

	err := s.db.QueryRow(query, id).Scan(
		&profile.ID,
		&profile.Name,
		&profile.Email,
		&profile.PhoneNumber,
		&profile.ProfileColor,
		&profile.CreatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("profile not found for user ID '%s': %w", id, err)
		}
		return nil, fmt.Errorf("failed to pull minimalist public profile metadata for user ID '%s': %w", id, err)
	}

	return &profile, nil
}

// ListUsers returns all active user accounts ordered alphabetically by name.
func (s *Store) ListUsers() ([]models.User, error) {
	query := `
	SELECT id, name, email, phone_number, balance_cents, credit_score, credit_limit_cents, is_active, profile_color, created_at
	FROM users
	WHERE is_active = 1
	ORDER BY name ASC;`

	rows, err := s.db.Query(query)
	if err != nil {
		return nil, fmt.Errorf("failed to execute full users table scan lookup query: %w", err)
	}
	defer rows.Close()

	users := []models.User{}

	for rows.Next() {
		var u models.User
		var isActiveInt int

		err := rows.Scan(
			&u.ID,
			&u.Name,
			&u.Email,
			&u.PhoneNumber,
			&u.BalanceCents,
			&u.CreditScore,
			&u.CreditLimitCents,
			&isActiveInt,
			&u.ProfileColor,
			&u.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan row into user data struct during list aggregation: %w", err)
		}

		u.IsActive = isActiveInt == 1
		users = append(users, u)
	}
	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("detected a mid-stream cursor failure during users rows iteration loop: %w", err)
	}
	return users, nil
}

// ListProfiles returns the public profiles of all active users, ordered alphabetically by name.
func (s *Store) ListProfiles() ([]models.Profile, error) {
	query := `
	SELECT id, name, email, phone_number, profile_color, created_at
	FROM users
	WHERE is_active = 1
	ORDER BY name ASC;`

	rows, err := s.db.Query(query)
	if err != nil {
		return nil, fmt.Errorf("failed to execute global public profiles query row collection: %w", err)
	}
	defer rows.Close()

	profiles := []models.Profile{}

	for rows.Next() {
		var profile models.Profile

		err := rows.Scan(
			&profile.ID,
			&profile.Name,
			&profile.Email,
			&profile.PhoneNumber,
			&profile.ProfileColor,
			&profile.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan matching profile data mapping structure: %w", err)
		}

		profiles = append(profiles, profile)
	}
	// Check for errors encountered during iteration
	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("detected a mid-stream cursor failure during profiles row iteration loop: %w", err)
	}
	return profiles, nil
}

// SearchProfiles performs a wildcard name and email search across all active user profiles.
func (s *Store) SearchProfiles(queryStr string) ([]models.Profile, error) {
	// Transform the query string into a SQL wildcard match format
	wildcardQuery := fmt.Sprintf("%%%s%%", queryStr)

	query := `
	SELECT id, name, email, phone_number, profile_color, created_at
	FROM users
	WHERE is_active = 1 AND (name LIKE ? OR email LIKE ?)
	ORDER BY name ASC;`

	rows, err := s.db.Query(query, wildcardQuery, wildcardQuery)
	if err != nil {
		return nil, fmt.Errorf("failed to execute profiles global search query for token '%s': %w", queryStr, err)
	}
	defer rows.Close()

	profiles := []models.Profile{}

	for rows.Next() {
		var p models.Profile
		err = rows.Scan(
			&p.ID,
			&p.Name,
			&p.Email,
			&p.PhoneNumber,
			&p.ProfileColor,
			&p.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan matching profile search record row: %w", err)
		}
		profiles = append(profiles, p)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("detected cursor failure mid-stream during profiles search loop execution:: %w", err)
	}

	return profiles, nil
}

// UpdatePassword overwrites the stored credential hash. Callers are responsible for securely
// hashing the new password externally before passing the digest to this method.
func (s *Store) UpdatePassword(userID, newHashedPassword string) error {
	query := `
	UPDATE users
	SET password_hash = ?
	WHERE id = ?;`

	result, err := s.db.Exec(query, newHashedPassword, userID)
	if err != nil {
		return fmt.Errorf("failed to execute credential mutation segment for user ID '%s': %w", userID, err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to read credential update metrics: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("credential mutation rejected: user ID '%s' not found", userID)
	}

	return nil
}

// UpdateEmail replaces the email address on record for a user account.
func (s *Store) UpdateEmail(userID, newEmail string) error {
	query := `
    UPDATE users
    SET email = ?
    WHERE id = ?;`

	result, err := s.db.Exec(query, newEmail, userID)
	if err != nil {
		return fmt.Errorf("failed to execute email mutation segment for user ID '%s': %w", userID, err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to read email update execution state metrics: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("email mutation rejected: user ID '%s' not found", userID)
	}

	return nil
}

// UpdatePhoneNumber replaces the phone number on record for a user account.
func (s *Store) UpdatePhoneNumber(userID, newPhoneNumber string) error {
	query := `
    UPDATE users
    SET phone_number = ?
    WHERE id = ?;`

	result, err := s.db.Exec(query, newPhoneNumber, userID)
	if err != nil {
		return fmt.Errorf("failed to execute phone number mutation segment for user ID '%s': %w", userID, err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to read phone number update execution state metrics: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("phone number mutation rejected: user ID '%s' not found", userID)
	}

	return nil
}

// UpdateDisplayName replaces the display name for a user account.
func (s *Store) UpdateDisplayName(userID, newName string) error {
	query := `
	UPDATE users
	SET name = ?
	WHERE id = ?;`

	result, err := s.db.Exec(query, newName, userID)
	if err != nil {
		return err
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return fmt.Errorf("display name update rejected: user ID '%s' not found", userID)
	}
	return nil
}

// DeactivateAccount performs a defensive soft-delete state transition by setting the is_active flag
// to false rather than purging the row, preserving ledger integrity.
func (s *Store) DeactivateAccount(userID string) error {
	query := `
	UPDATE users
	SET is_active = 0
	WHERE id = ?;`

	result, err := s.db.Exec(query, userID)
	if err != nil {
		return fmt.Errorf("failed to execute account deactivation state transition for user ID '%s': %w", userID, err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to read account deactivation execution state metrics: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("account deactivation rejected: user ID '%s' not found in user registry", userID)
	}

	return nil
}

// UpdateCreditScore applies a signed delta to a user's credit score, clamping the result
// between 0 and 100 to prevent overflow or underflow.
func (s *Store) UpdateCreditScore(userID string, delta int) error {
	// Clamp the resulting score between 0 and 100 to prevent overflow or underflow
	query := `
	UPDATE users
	SET credit_score = MIN(100, MAX(0, credit_score + ?))
	WHERE id = ?`

	result, err := s.db.Exec(query, delta, userID)
	if err != nil {
		return fmt.Errorf("failed to apply credit score adjustment of %+d points to user ID '%s': %w", delta, userID, err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to read credit score adjustment execution state metrics: %w", err)
	}
	if rowsAffected == 0 {
		return fmt.Errorf("credit score adjustment rejected: user account ID '%s' not found in user registry", userID)
	}

	return nil
}

// UpdateProfileColor persists a new CSS avatar color class for a user account.
func (s *Store) UpdateProfileColor(userID, color string) error {
	result, err := s.db.Exec(`UPDATE users SET profile_color = ? WHERE id = ?;`, color, userID)
	if err != nil {
		return fmt.Errorf("failed to update profile color for user '%s': %w", userID, err)
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to read profile color update metrics: %w", err)
	}
	if rows == 0 {
		return fmt.Errorf("profile color update rejected: user ID '%s' not found", userID)
	}
	return nil
}
